export const productsList = [
  { id: 1, name: 'Crown Extra', enabled: true, code: 'crownExtra', image: null, logo: '', type: 'website', description: 'These distinctively northern English style ales have a strong, malty center and can be nutty, sweet and very lightly hopped.', url: '', reset_password_url: '', track_order_url: '', social: null },
  { id: 2, name: 'Green bee', enabled: true, code: 'greenBee', image: null, logo: '', type: 'app', description: 'Very similar to stout but made from, or largely from, unroasted barley.', url: '', reset_password_url: '', track_order_url: '', social: null },
  { id: 3, name: 'Steel Beer', enabled: false, code: 'steelBeer', image: null, logo: '', type: 'website', description: 'Whether American or English, the “pale” was clipped on long ago to distinguish it from the dark color of Porters.', url: '', reset_password_url: '', track_order_url: '', social: null },
  { id: 4, name: 'X2 Lager', enabled: true, code: 'x2Lager', image: null, logo: '', type: 'website', description: 'Yuengling, Killian’s, Brooklyn Lager) – More malt and darker than their lighter lager relatives, usually amber to copper colored.', url: '', reset_password_url: '', track_order_url: '', social: null },
  { id: 5, name: 'Guin ESS', enabled: true, code: 'GuinEss', image: null, logo: '', type: 'app', description: 'Pale ale with intense hop flavor and aroma and slightly higher alcohol content.', url: '', reset_password_url: '', track_order_url: '', social: null },
  { id: 6, name: 'GRILY 3', enabled: true, code: 'grily3', image: null, logo: '', type: 'website', description: '19 ounces of sheer perfection—full-bodied and full of flavor. Ruth\'s favorite cut.', url: '', reset_password_url: '', track_order_url: '', social: null },
  { id: 7, name: 'GRILL 2', enabled: true, code: 'grill2', image: null, logo: '', type: 'website', description: '40 ounces of prime beef with the rich flavor of a strip and the tenderness of a filet.', url: '', reset_password_url: '', track_order_url: '', social: null },
  { id: 8, name: 'GRILL 1', enabled: true, code: 'grill1', image: null, logo: '', type: 'website', description: 'Tender filet and hearty New York Strip combined into one 24-ounce USDA Prime cut.', url: '', reset_password_url: '', track_order_url: '', social: null },
  { id: 9, name: 'RIBS', enabled: true, code: 'ribs', image: null, logo: '', type: 'website', description: '19 ounces of sheer perfection—full-bodied and full of flavor. Ruth\'s favorite cut.', url: '', reset_password_url: '', track_order_url: '', social: null },
  { id: 10, name: 'SPECIALTY', enabled: false, code: 'specialty', image: null, logo: '', type: 'website', description: 'A 16-ounce full-flavored USDA Prime cut, with a slightly firmer texture than a ribeye.', url: '', reset_password_url: '', track_order_url: '', social: null },
  { id: 11, name: 'RIB EYE', enabled: true, code: 'ribEye', image: null, logo: '', type: 'website', description: 'A 16-ounce cut of rich USDA Prime beef that\'s well marbled and deliciously juicy.', url: '', reset_password_url: '', track_order_url: '', social: null },
  { id: 12, name: 'SIRLOIN', enabled: true, code: 'sirloin', image: null, logo: '', type: 'website', description: '11 ounces of our most tender cut of lean, midwestern beef.', url: '', reset_password_url: '', track_order_url: '', social: null },
  { id: 13, name: 'Dress with Trim', enabled: false, code: 'dressTrim', image: null, logo: '', type: 'website', description: '11 ounces of our most tender cut of lean, midwestern beef.', url: '', reset_password_url: '', track_order_url: '', social: null },
  { id: 14, name: 'Dress (Everyday)', enabled: true, code: 'dressEveryday', image: null, logo: '', type: 'website', description: 'Very similar to stout but made from, or largely from, unroasted barley.', url: '', reset_password_url: '', track_order_url: '', social: null },
  { id: 15, name: 'Blouse', enabled: true, code: 'blouse', image: null, logo: '', type: 'website', description: 'These distinctively northern English style ales have a strong, malty center and can be nutty', url: '', reset_password_url: '', track_order_url: '', social: null },
  { id: 16, name: 'Shirt', enabled: true, code: 'shirt', image: null, logo: '', type: 'website', description: 'Very similar to stout but made from, or largely from, unroasted barley.', url: '', reset_password_url: '', track_order_url: '', social: null },
  { id: 17, name: 'Large Laundry Bag', enabled: true, code: 'largeLaundryBag', image: null, logo: '', type: 'website', description: 'These distinctively northern English style ales have a strong, malty center and can be nutty', url: '', reset_password_url: '', track_order_url: '', social: null }
]
