"use strict";

function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.UploadedImages = exports.UploadImageIconContainer = exports.UploadImageIcon = exports.UploadConditions = exports.Title = exports.SkeletonWrapper = exports.IssueBoard = exports.ImageIssue = exports.ImageInput = exports.FormContainer = exports.Container = exports.Conditions = exports.ConditionTitle = exports.BatchUploadForm = exports.BatchImages = exports.Action = void 0;
var _styledComponents = _interopRequireWildcard(require("styled-components"));
var _polished = require("polished");
var _templateObject, _templateObject2, _templateObject3, _templateObject4, _templateObject5, _templateObject6, _templateObject7, _templateObject8, _templateObject9, _templateObject10, _templateObject11, _templateObject12, _templateObject13, _templateObject14, _templateObject15, _templateObject16, _templateObject17;
function _getRequireWildcardCache(e) { if ("function" != typeof WeakMap) return null; var r = new WeakMap(), t = new WeakMap(); return (_getRequireWildcardCache = function _getRequireWildcardCache(e) { return e ? t : r; })(e); }
function _interopRequireWildcard(e, r) { if (!r && e && e.__esModule) return e; if (null === e || "object" != _typeof(e) && "function" != typeof e) return { default: e }; var t = _getRequireWildcardCache(r); if (t && t.has(e)) return t.get(e); var n = { __proto__: null }, a = Object.defineProperty && Object.getOwnPropertyDescriptor; for (var u in e) if ("default" !== u && {}.hasOwnProperty.call(e, u)) { var i = a ? Object.getOwnPropertyDescriptor(e, u) : null; i && (i.get || i.set) ? Object.defineProperty(n, u, i) : n[u] = e[u]; } return n.default = e, t && t.set(e, n), n; }
function _taggedTemplateLiteral(strings, raw) { if (!raw) { raw = strings.slice(0); } return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }
var Container = exports.Container = _styledComponents.default.div(_templateObject || (_templateObject = _taggedTemplateLiteral(["\n  width: 100%;\n"])));
var Title = exports.Title = _styledComponents.default.div(_templateObject2 || (_templateObject2 = _taggedTemplateLiteral(["\n  display: flex;\n  justify-content: flex-start;\n  margin-top: 20px;\n  margin-bottom: 20px;\n  h2 {\n    font-style: normal;\n    font-weight: bold;\n    font-size: 20px;\n    line-height: 30px;\n    margin: 0;\n    color: ", ";\n  }\n  @media (min-width: 768px) {\n    margin-bottom: 25px;\n    h2 {\n      font-size: 24px;\n    }\n  }\n"])), function (props) {
  var _props$theme$colors;
  return (_props$theme$colors = props.theme.colors) === null || _props$theme$colors === void 0 ? void 0 : _props$theme$colors.headingColor;
});
var UploadConditions = exports.UploadConditions = _styledComponents.default.div(_templateObject3 || (_templateObject3 = _taggedTemplateLiteral(["\n  display: block;\n"])));
var ConditionTitle = exports.ConditionTitle = _styledComponents.default.p(_templateObject4 || (_templateObject4 = _taggedTemplateLiteral(["\n  margin: 0;\n  margin-bottom: 9px;\n  font-style: normal;\n  font-weight: 500;\n  font-size: 14px;\n  line-height: 21px;\n  color: ", ";\n  @media (min-width: 768px) {\n    font-size: 16px;\n    line-height: 28px;\n  }\n"])), function (props) {
  var _props$theme$colors2;
  return (_props$theme$colors2 = props.theme.colors) === null || _props$theme$colors2 === void 0 ? void 0 : _props$theme$colors2.headingColor;
});
var Conditions = exports.Conditions = _styledComponents.default.ol(_templateObject5 || (_templateObject5 = _taggedTemplateLiteral(["\n  padding-left: 15px;\n  li {\n    margin: 0;\n    font-style: normal;\n    font-weight: normal;\n    font-size: 14px;\n    line-height: 24px;\n    color: ", ";\n  }\n  @media (min-width: 768px) {\n    padding-left: 20px;\n    li {\n      font-size: 16px;\n    }\n  }\n"])), function (props) {
  var _props$theme$colors3;
  return (_props$theme$colors3 = props.theme.colors) === null || _props$theme$colors3 === void 0 ? void 0 : _props$theme$colors3.headingColor;
});
var FormContainer = exports.FormContainer = _styledComponents.default.div(_templateObject6 || (_templateObject6 = _taggedTemplateLiteral(["\n  display: flex;\n  flex-direction: column;\n  @media (min-width: 768px) {\n    flex-direction: row;\n    margin-top: 30px;\n  }\n"])));
var BatchUploadForm = exports.BatchUploadForm = _styledComponents.default.form(_templateObject7 || (_templateObject7 = _taggedTemplateLiteral(["\n  width: 100%;\n  height: fit-content;\n  margin: 0 auto;\n\n  @media (min-width: 768px) {\n    width: 50%;\n  }\n"])));
var ImageIssue = exports.ImageIssue = _styledComponents.default.div(_templateObject8 || (_templateObject8 = _taggedTemplateLiteral(["\n  position: relative;\n  width: 100%;\n  p {\n    margin: 0;\n    margin-bottom: 9px;\n    font-style: normal;\n    font-weight: 500;\n    font-size: 14px;\n    line-height: 21px;\n  }\n  ul {\n    padding-left: 0px;\n    margin-bottom: 0;\n    list-style-type: circle;\n    li {\n      display: block;\n      white-space: nowrap;\n      overflow: hidden;\n      text-overflow: ellipsis;\n      font-size: 14px;\n      line-height: 24px;\n    }\n  }\n\n  @media (min-width: 768px) {\n    width: 50%;\n    padding: 0 20px;\n    border-left: 1px solid #E9ECEF;\n    margin-left: 25px;\n    &:after {\n      content:'';\n      position: absolute;\n      left: -1px;\n      bottom: 0;\n      background: ", ";\n      width: 2px;\n      height: 55px;\n    }\n  }\n  \n"])), function (props) {
  var _props$theme$colors4;
  return ((_props$theme$colors4 = props.theme.colors) === null || _props$theme$colors4 === void 0 ? void 0 : _props$theme$colors4.backgroundPage) || '#FFF';
});
var ImageInput = exports.ImageInput = _styledComponents.default.div(_templateObject9 || (_templateObject9 = _taggedTemplateLiteral(["\n  padding: 20px;\n  @media (min-width: 768px) {\n    padding: 0px;\n  }\n"])));
var BatchImages = exports.BatchImages = _styledComponents.default.div(_templateObject10 || (_templateObject10 = _taggedTemplateLiteral(["\n  position:relative;\n  width: 100%;\n  .multiple-image-uploader {\n    position: relative;\n    width: 100%;\n    padding-top: 75%; \n  }\n"])));
var SkeletonWrapper = exports.SkeletonWrapper = _styledComponents.default.div(_templateObject11 || (_templateObject11 = _taggedTemplateLiteral(["\n  position: absolute;\n  width: 100%;\n  height: 100%;\n  box-sizing: border-box;\n  padding: 11px;\n  top: 0;\n  left: 0;\n  display: flex;\n  flex-direction: column;\n  justify-content: center;\n  align-items: center;\n  z-index: 20;\n  .loader-wrapper {\n    width: 40px;\n    height: 40px;\n    justify-content: center;\n    align-items: center;\n  }\n  .loader {\n      width: 30px;\n      height: 30px;\n      top: 50%;\n      left: 50%;\n      border-radius: 60px;\n      animation: loader 0.8s linear infinite;\n      -webkit-animation: loader 0.8s linear infinite;\n  }\n\n  @keyframes loader {\n    0% {\n      -webkit-transform: rotate(0deg);\n      transform: rotate(0deg);\n      border: 4px solid #2C7BE5;\n      border-left-color: transparent;\n    }\n    50% {\n      -webkit-transform: rotate(180deg);\n      transform: rotate(180deg);\n      border: 4px solid ", ";\n      border-left-color: transparent;\n    }\n    100% {\n      -webkit-transform: rotate(360deg);\n      transform: rotate(360deg);\n      border: 4px solid ", ";\n      border-left-color: transparent;\n    }\n  }\n"])), function () {
  return (0, _polished.darken)(0.06, '#2C7BE5');
}, function () {
  return (0, _polished.darken)(0.03, '#2C7BE5');
});
var UploadImageIconContainer = exports.UploadImageIconContainer = _styledComponents.default.div(_templateObject12 || (_templateObject12 = _taggedTemplateLiteral(["\n  background: #E9ECEF;\n  top: 0;\n  left: 0;\n  bottom: 0;\n  right: 0;\n  text-align: center;\n  position:  absolute;\n  padding:10px;\n  border-radius: 7.6px;\n"])));
var UploadImageIcon = exports.UploadImageIcon = _styledComponents.default.div(_templateObject13 || (_templateObject13 = _taggedTemplateLiteral(["\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  flex-direction: column;\n  color: #ADB5BD;\n  border: 1px dashed #fff;\n  width: 100%;\n  height: 100%;\n  span {\n    margin: 0;\n  }\n  svg {   \n    width: 45px;\n    height: 45px;\n  }\n"])));
var Action = exports.Action = _styledComponents.default.div(_templateObject14 || (_templateObject14 = _taggedTemplateLiteral(["\n  display: flex;\n  width: 100%;\n  padding: 20px;\n  padding-top: 0;\n\n  button {\n    width: 100%;\n    @media (min-width: 768px) {\n      width: fit-content;\n    }\n  }\n\n  @media (min-width: 768px) {\n    padding: 0px;\n    padding-top: 20px;\n  }\n"])));
var IssueBoard = exports.IssueBoard = _styledComponents.default.div(_templateObject15 || (_templateObject15 = _taggedTemplateLiteral(["\n  display: flex;\n  width: 100%;\n  height: fit-content;\n  border-radius: 7.6px;\n  padding: 10px;\n  border: 1px ridge #f2f2f2;\n  max-height: 150px;\n  overflow-y: auto;\n  ", "\n"])), function (props) {
  return props.emptyboard && (0, _styledComponents.css)(_templateObject16 || (_templateObject16 = _taggedTemplateLiteral(["\n    min-height: 75px;\n  "])));
});
var UploadedImages = exports.UploadedImages = _styledComponents.default.div(_templateObject17 || (_templateObject17 = _taggedTemplateLiteral(["\n  position: absolute;\n  width: 100%;\n  padding: 11px;\n  top: 0;\n  left: 0;\n  display: flex;\n  flex-wrap: wrap;\n  z-index: 20;\n  img {\n    width: 18.6%;\n    min-height: 24%;\n    object-fit: cover;\n    margin: 2px;\n  }\n\n"])));