"use strict";

function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.WrapperOrderlabel = exports.WrapperGeneralInfo = exports.WrapperDriverSelector = exports.WrapperAccordionImage = exports.WrapOrderQuickDetail = exports.TextBlockContainer = exports.SmallText = exports.OrderItemAccordionContainer = exports.OrderItemAccordionCell = exports.OrderInfoContainer = exports.OrderDetailToggleButton = exports.DeliveryTypeContainer = exports.DeliveryName = exports.DeliveryIcon = exports.CheckBoxContainer = exports.BigText = exports.AccordionSection = exports.AccordionImage = void 0;
var _react = _interopRequireWildcard(require("react"));
var _styledComponents = _interopRequireDefault(require("styled-components"));
var _templateObject, _templateObject2, _templateObject3, _templateObject4, _templateObject5, _templateObject6, _templateObject7, _templateObject8, _templateObject9, _templateObject10, _templateObject11, _templateObject12, _templateObject13, _templateObject14, _templateObject15, _templateObject16, _templateObject17, _templateObject18, _templateObject19;
function _interopRequireDefault(e) { return e && e.__esModule ? e : { default: e }; }
function _getRequireWildcardCache(e) { if ("function" != typeof WeakMap) return null; var r = new WeakMap(), t = new WeakMap(); return (_getRequireWildcardCache = function _getRequireWildcardCache(e) { return e ? t : r; })(e); }
function _interopRequireWildcard(e, r) { if (!r && e && e.__esModule) return e; if (null === e || "object" != _typeof(e) && "function" != typeof e) return { default: e }; var t = _getRequireWildcardCache(r); if (t && t.has(e)) return t.get(e); var n = { __proto__: null }, a = Object.defineProperty && Object.getOwnPropertyDescriptor; for (var u in e) if ("default" !== u && {}.hasOwnProperty.call(e, u)) { var i = a ? Object.getOwnPropertyDescriptor(e, u) : null; i && (i.get || i.set) ? Object.defineProperty(n, u, i) : n[u] = e[u]; } return n.default = e, t && t.set(e, n), n; }
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
function _taggedTemplateLiteral(e, t) { return t || (t = e.slice(0)), Object.freeze(Object.defineProperties(e, { raw: { value: Object.freeze(t) } })); }
var AccordionSection = exports.AccordionSection = _styledComponents.default.div(_templateObject || (_templateObject = _taggedTemplateLiteral(["\n  display: flex;\n  flex-direction: column;\n  width: 100%;\n  background: ", ";\n  cursor: pointer;\n"])), function (props) {
  var _props$theme$colors;
  return ((_props$theme$colors = props.theme.colors) === null || _props$theme$colors === void 0 ? void 0 : _props$theme$colors.backgroundPage) || '#FFF';
});
var OrderItemAccordionContainer = exports.OrderItemAccordionContainer = _styledComponents.default.div(_templateObject2 || (_templateObject2 = _taggedTemplateLiteral(["\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  box-shadow: 0px 0px 3px #00000029;\n  border-radius: 6px;\n  border-left: 7px solid;\n  border-color: ", ";\n  margin-bottom: 10px;\n  position: initial;\n\n  & > div {\n    &: first-child {\n      width: 15%;\n      min-width: 180px;\n      align-items: center;\n      column-gap: 0px;\n      padding: 0px;\n      & > div {\n        &:first-child {\n          padding: 0 5px;\n          height: 90px;\n          display: flex;\n          align-items: center;\n        }\n      }    \n    }\n  }\n"])), function (_ref) {
  var filterColor = _ref.filterColor;
  return filterColor || '#0E9B55';
});
var OrderItemAccordionCell = exports.OrderItemAccordionCell = _styledComponents.default.div(_templateObject3 || (_templateObject3 = _taggedTemplateLiteral(["\n  display: flex;\n  column-gap: 8px;\n  padding: 15px 0;\n\n  .rotate {\n    transform: rotate(180deg);\n  }\n\n  .accordion__icon {\n    margin-left: auto;\n    transition: transform 0.6s ease;\n    ", "\n  }\n\n  & > div {\n    & > div {\n      &:first-child {\n        p {\n          margin: 0px;\n          white-space: nowrap;\n          text-overflow: ellipsis;\n          overflow: hidden;\n          max-width: 165px;   \n        }\n      }\n    }\n  }\n"])), function (props) {
  var _props$theme;
  return ((_props$theme = props.theme) === null || _props$theme === void 0 ? void 0 : _props$theme.rtl) && (0, _react.css)(_templateObject4 || (_templateObject4 = _taggedTemplateLiteral(["\n      margin-right: auto;\n      margin-left: initial;\n    "])));
});
var CheckBoxContainer = exports.CheckBoxContainer = _styledComponents.default.div(_templateObject5 || (_templateObject5 = _taggedTemplateLiteral(["\n  color: #404040;\n  svg {\n    width: 20px;\n    height: 20px;\n    circle {\n      fill: #ccc;\n    }\n  }\n\n  &:hover {\n    svg {\n      circle {\n        fill: #404040;\n      }\n    }\n  }\n"])));
var WrapperAccordionImage = exports.WrapperAccordionImage = _styledComponents.default.div(_templateObject6 || (_templateObject6 = _taggedTemplateLiteral(["\n  max-width: 45px;\n  max-height: 45px;\n  height: 45px;\n  width: 45px;\n  border: 1px solid #E3E3E3;\n  border-radius: 10px;\n\n  svg {\n    width: 100%;\n    height: 100%;\n    padding: 7px;\n    box-sizing: border-box;\n    border-radius: 50%;\n  }\n"])));
var AccordionImageStyled = _styledComponents.default.div(_templateObject7 || (_templateObject7 = _taggedTemplateLiteral(["\n  display: flex;\n  width: 100%;\n  height: 100%;\n  box-sizing: border-box;\n  position: relative;\n  background-repeat: no-repeat, repeat;\n  background-size: cover;\n  object-fit: cover;\n  background-position: center;\n  border-radius: 10px;\n"])));
var AccordionImage = exports.AccordionImage = function AccordionImage(props) {
  return /*#__PURE__*/_react.default.createElement(AccordionImageStyled, _extends({}, props, {
    style: {
      backgroundImage: "url(".concat(props.bgimage, ")")
    }
  }), props.children);
};
var TextBlockContainer = exports.TextBlockContainer = _styledComponents.default.div(_templateObject8 || (_templateObject8 = _taggedTemplateLiteral(["\n  flex: 1;\n  overflow: hidden;\n  display: flex;\n  flex-direction: column;\n  justify-content: center;\n"])));
var BigText = exports.BigText = _styledComponents.default.p(_templateObject9 || (_templateObject9 = _taggedTemplateLiteral(["\n  color: #000000;\n  margin: 0px;\n  font-weight: 600;\n  overflow: hidden;\n  text-overflow: ellipsis;\n  white-space: nowrap;\n  font-size: 14px;\n"])));
var SmallText = exports.SmallText = _styledComponents.default.p(_templateObject10 || (_templateObject10 = _taggedTemplateLiteral(["\n  color: #343434;\n  font-size: 12px;\n  margin: 0px;\n  overflow: hidden;\n  text-overflow: ellipsis;\n  white-space: nowrap;\n"])));
var DeliveryTypeContainer = exports.DeliveryTypeContainer = _styledComponents.default.div(_templateObject11 || (_templateObject11 = _taggedTemplateLiteral(["\n  display: flex;\n  flex-direction: column;\n  justify-content: center;\n  align-items: center;\n"])));
var DeliveryIcon = exports.DeliveryIcon = _styledComponents.default.div(_templateObject12 || (_templateObject12 = _taggedTemplateLiteral(["\n  width: 25px;\n  height: 30px;\n\n  img {\n    width: 100%;\n    height: 100%;\n    border-radius: unset;\n    border: none;\n  }\n\n  svg {\n    width: 100%;\n    height: 100%;\n  }\n"])));
var DeliveryName = exports.DeliveryName = _styledComponents.default.p(_templateObject13 || (_templateObject13 = _taggedTemplateLiteral(["\n  margin: 0px;\n  color: #343434;  \n  font-size: 9px;\n"])));
var OrderDetailToggleButton = exports.OrderDetailToggleButton = _styledComponents.default.span(_templateObject14 || (_templateObject14 = _taggedTemplateLiteral(["\n  cursor: pointer;\n  margin: 0 5px;\n  margin-top: 3px;\n"])));
var WrapperDriverSelector = exports.WrapperDriverSelector = _styledComponents.default.div(_templateObject15 || (_templateObject15 = _taggedTemplateLiteral(["\n  > div {\n    border: none;\n    margin: 0 -15px;\n  }\n"])));
var OrderInfoContainer = exports.OrderInfoContainer = _styledComponents.default.div(_templateObject16 || (_templateObject16 = _taggedTemplateLiteral(["\n  flex: 1;\n"])));
var WrapperGeneralInfo = exports.WrapperGeneralInfo = _styledComponents.default.div(_templateObject17 || (_templateObject17 = _taggedTemplateLiteral(["\n  width: 100%;\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  border-bottom: 1px solid #e8e8e8;\n\n  & > div {\n    \n    &:nth-child(1) {\n      width: 20%;\n      min-width: 150px;\n    }\n\n    &:nth-child(2) {\n      width: 20%;\n      min-width: 150px;\n    }\n\n    &:nth-child(3) {\n      width: 23%;\n      min-width: 150px;\n      padding: 0px;\n      p {\n        font-size: 14px;\n        font-weight: 600;\n      }\n    }\n\n    &:nth-child(4) {\n      min-width: 40px;\n      width: 6%;\n      font-size: 14px;\n    }\n\n    \n    &:nth-child(5) {\n      width: 22%;\n      min-width: 170px;\n      display: block;\n      justify-content: initial;\n      text-align: center;\n\n      p {\n        font-size: 12px;\n      }\n    }\n\n    &:nth-child(6) {\n      width: 9%;\n      width: 9%;\n      min-width: 120px;\n      display: flex;\n      justify-content: flex-end;\n    }\n  }\n\n  @media (max-width: 1200px) {\n    & > div {\n      &:nth-child(3),\n      &:nth-child(4) {\n        display: none;\n      }\n    }\n  }\n"])));
var WrapperOrderlabel = exports.WrapperOrderlabel = _styledComponents.default.div(_templateObject18 || (_templateObject18 = _taggedTemplateLiteral(["\n  width: 100%;\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n\n  & > div {\n    &:nth-child(1) {\n      width: 20%;\n    }\n\n    &:nth-child(2) {\n      width: 20%;\n    }\n\n    &:nth-child(3) {\n      width: 23%;\n    }\n\n    &:nth-child(4) {\n      flex: 1;\n      justify-content: flex-end;\n      margin: 0 5px;\n    }\n  }\n\n  @media (max-width: 1200px) {\n    & > div {\n      &:nth-child(1),\n      &:nth-child(2) {\n        width: 29%;\n      }\n    }\n  }\n"])));
var WrapOrderQuickDetail = exports.WrapOrderQuickDetail = _styledComponents.default.div(_templateObject19 || (_templateObject19 = _taggedTemplateLiteral([""])));